from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def _build_argo_lookup(
    argo_match_csv: Path,
) -> tuple[dict[int, int], dict[str, str]]:
    """Build date/month lookup maps from Argo datetime match CSV."""
    if not argo_match_csv.exists():
        raise FileNotFoundError(f"Argo match CSV not found: {argo_match_csv}")

    day_counts: dict[int, int] = defaultdict(int)
    month_file: dict[str, str] = {}

    with argo_match_csv.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {
            "argo_month_key",
            "matched_ostia_date",
            "argo_file_path",
        }
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise RuntimeError(
                f"Argo match CSV missing required columns: {sorted(missing)}"
            )

        for row in reader:
            day_raw = row.get("matched_ostia_date", "").strip()
            if not day_raw:
                continue
            try:
                day_int = int(day_raw)
            except ValueError:
                continue
            if day_int <= 0:
                continue
            day_counts[day_int] += 1

            month_key = str(row.get("argo_month_key", "")).strip()
            argo_path = str(row.get("argo_file_path", "")).strip()
            if month_key and month_key not in month_file and argo_path:
                month_file[month_key] = argo_path

    return dict(day_counts), month_file


def merge_argo_into_daily_index(
    *,
    daily_csv: Path,
    argo_match_csv: Path,
    output_csv: Path,
) -> Path:
    """Merge Argo validity/metadata columns into daily OSTIA patch CSV."""
    if not daily_csv.exists():
        raise FileNotFoundError(f"Daily CSV not found: {daily_csv}")

    day_counts, month_file = _build_argo_lookup(argo_match_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    with (
        daily_csv.open("r", newline="", encoding="utf-8") as src_f,
        output_csv.open("w", newline="", encoding="utf-8") as dst_f,
    ):
        reader = csv.DictReader(src_f)
        if not reader.fieldnames:
            raise RuntimeError(f"Daily CSV has no header: {daily_csv}")
        if "date" not in reader.fieldnames:
            raise RuntimeError("Daily CSV is missing required column: date")

        fieldnames = list(reader.fieldnames) + [
            "argo_valid",
            "argo_profile_count",
            "argo_month_key",
            "argo_file_path",
        ]
        writer = csv.DictWriter(dst_f, fieldnames=fieldnames)
        writer.writeheader()

        for row in reader:
            date_raw = str(row.get("date", "")).strip()
            try:
                day_int = int(date_raw)
            except ValueError:
                day_int = 0

            day_count = int(day_counts.get(day_int, 0))
            month_key = str(day_int).zfill(8)[:6] if day_int > 0 else ""
            row["argo_valid"] = "1" if day_count > 0 else "0"
            row["argo_profile_count"] = str(day_count)
            row["argo_month_key"] = month_key
            row["argo_file_path"] = month_file.get(month_key, "")
            writer.writerow(row)

    return output_csv


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Merge Argo datetime-match info into the OSTIA daily patch index CSV "
            "to produce one single source-of-truth CSV."
        )
    )
    parser.add_argument(
        "--daily-csv",
        type=Path,
        default=Path("/data1/datasets/depth_v2/ostia_patch_index_daily.csv"),
        help="Input OSTIA daily patch index CSV.",
    )
    parser.add_argument(
        "--argo-match-csv",
        type=Path,
        default=Path("/data1/datasets/depth_v2/argo_profile_datetime_match.csv"),
        help="Argo datetime match CSV generated by build_argo_datetime_match_index.py.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path("/data1/datasets/depth_v2/ostia_patch_index_daily.csv"),
        help="Output CSV path (can be same as --daily-csv).",
    )
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    daily_csv = args.daily_csv
    output_csv = args.output_csv
    if daily_csv.resolve() == output_csv.resolve():
        # Avoid truncating the input while reading by writing to a temp sibling first.
        temp_out = output_csv.with_name(output_csv.name + ".tmp_with_argo")
    else:
        temp_out = output_csv

    out = merge_argo_into_daily_index(
        daily_csv=daily_csv,
        argo_match_csv=args.argo_match_csv,
        output_csv=temp_out,
    )

    if temp_out != output_csv:
        temp_out.replace(output_csv)
    print(f"Wrote merged single-source CSV: {output_csv}")


if __name__ == "__main__":
    main()

